# RabbitMQ — Phase 8 standalone manifest, ns rabbit
# Secret rabbitmq-secret: dùng ExternalSecret (vault/) thay kubectl create
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-rabbitmq
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: phase9-gitops
    app.kubernetes.io/component: rabbitmq
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: banking-platform
  source:
    repoURL: https://github.com/YOUR_ORG/banking-demo.git
    targetRevision: main
    path: phase8-application-v3/rabbitmq
    directory:
      include: k8s-rabbitmq-standalone.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbit
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
