apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: banking-db-secret
  namespace: banking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: banking-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: banking/db
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: banking/db
        property: REDIS_URL
