FROM python:3.11-slim

LABEL org.opencontainers.image.source=https://github.com/nnhattruong30/banking-demo

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy common library
COPY common /app/common

# Copy service files
COPY services/auth-service /app

# Install dependencies
RUN pip install --no-cache-dir -r common/requirements.txt

EXPOSE 8001
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
