# ArgoCD/Helm merge theo key frontend
frontend:
  fullnameOverride: frontend
  enabled: true
  image:
    repository: ghcr.io/nnhattruong30/banking-demo/frontend
    tag: latest
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: github-registry
  replicas: 1
  service:
    port: 80
    portName: http
  readinessProbe:
    enabled: true
    path: /
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  securityContext:
    pod:
      seccompProfile:
        type: RuntimeDefault
    container:
      allowPrivilegeEscalation: false
